spring:
  application:
    name: spring-batch-demo
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
server:
  port: 9000
